version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  build:
    docker:
      - image: circleci/node:16.9.1
    working_directory: ~/repo
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run tests
          command: yarn test:ci

workflows:
  test:
    jobs:
      - build