import type { NextPage } from 'next'
import Head from 'next/head'
import { Spin } from 'antd'
import { LoadingOutlined } from '@ant-design/icons' 

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Elevated Code</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        
        <LoadingOutlined style={{ fontSize: 24 }} spin />
      </main>
      <footer></footer>
    </div>
  )
}

export default Home
